"""esquema inicial: tablas curadas

Revision ID: b0d7bbdb6257
Revises: 
Create Date: 2026-09-15 19:37:54.460715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0d7bbdb6257'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('empresa_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id')
    )
    op.create_table('historico_cierres',
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('canal', sa.String(), nullable=True),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('punto_venta_id', sa.String(), nullable=True),
    sa.Column('modelo_cotizado', sa.String(), nullable=True),
    sa.Column('precio_lista', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('horas_al_primer_contacto', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('numero_contactos', sa.Integer(), nullable=True),
    sa.Column('manifesto_cuota_inicial', sa.String(), nullable=True),
    sa.Column('forma_pago_declarada', sa.String(), nullable=True),
    sa.Column('pidio_cita', sa.String(), nullable=True),
    sa.Column('desenlace', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('motos_catalogo',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('linea', sa.String(), nullable=False),
    sa.Column('cilindraje', sa.String(), nullable=True),
    sa.Column('segmento', sa.String(), nullable=True),
    sa.Column('precio_lista', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('clientes',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre_normalizado', sa.Text(), nullable=True),
    sa.Column('telefono_normalizado', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ciudad_normalizada', sa.String(), nullable=True),
    sa.Column('empresa_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ),
    sa.PrimaryKeyConstraint('cliente_id'),
    sa.UniqueConstraint('telefono_normalizado', 'empresa_id', name='uq_cliente_telefono_empresa')
    )
    op.create_table('puntos_venta',
    sa.Column('punto_venta_id', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ),
    sa.PrimaryKeyConstraint('punto_venta_id')
    )
    op.create_table('asesores',
    sa.Column('asesor_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('punto_venta_id', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=False),
    sa.Column('capacidad_diaria_leads', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.punto_venta_id'], ),
    sa.PrimaryKeyConstraint('asesor_id')
    )
    op.create_table('leads',
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.String(), nullable=False),
    sa.Column('punto_venta_id', sa.String(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('modelo_interes_texto', sa.Text(), nullable=True),
    sa.Column('sku_matcheado', sa.String(), nullable=True),
    sa.Column('estado_gestion', sa.String(), nullable=False),
    sa.Column('fecha_primer_contacto', sa.DateTime(), nullable=True),
    sa.Column('campania', sa.String(), nullable=True),
    sa.CheckConstraint("canal IN ('WhatsApp', 'Meta Ads', 'Formulario Web')", name='ck_lead_canal_valido'),
    sa.CheckConstraint("estado_gestion IN ('Contactado', 'Sin gestión', 'Cotización enviada', 'En proceso', 'No contesta', 'Descartado')", name='ck_lead_estado_valido'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.punto_venta_id'], ),
    sa.ForeignKeyConstraint(['sku_matcheado'], ['motos_catalogo.sku'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('motos_disponibilidad',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('punto_venta_id', sa.String(), nullable=False),
    sa.Column('unidades_disponibles', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.punto_venta_id'], ),
    sa.ForeignKeyConstraint(['sku'], ['motos_catalogo.sku'], ),
    sa.PrimaryKeyConstraint('sku', 'punto_venta_id')
    )
    op.create_table('asignaciones',
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('asesor_id', sa.String(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asesor_id'], ['asesores.asesor_id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('lead_enriquecimiento',
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('conversacion_id', sa.String(), nullable=False),
    sa.Column('modelo_interes_ia', sa.Text(), nullable=True),
    sa.Column('presupuesto_cuota_inicial', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('forma_pago_declarada', sa.String(), nullable=True),
    sa.Column('intencion_declarada', sa.Text(), nullable=True),
    sa.Column('objecion_principal', sa.Text(), nullable=True),
    sa.Column('pidio_cita', sa.Boolean(), nullable=False),
    sa.Column('confianza_extraccion', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('lead_score',
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('temperatura', sa.String(), nullable=False),
    sa.Column('factores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=False),
    sa.CheckConstraint("temperatura IN ('Frío', 'Tibio', 'Caliente')", name='ck_temperatura_valida'),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name='ck_score_rango'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )

    op.create_index('idx_leads_empresa', 'leads', ['empresa_id'])
    op.create_index('idx_leads_punto_venta', 'leads', ['punto_venta_id'])
    op.create_index('idx_leads_estado', 'leads', ['estado_gestion'])
    op.create_index('idx_clientes_empresa', 'clientes', ['empresa_id'])
    op.create_index('idx_asignaciones_asesor', 'asignaciones', ['asesor_id'])
    op.create_index('idx_lead_score_temperatura', 'lead_score', ['temperatura'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lead_score_temperatura', table_name='lead_score')
    op.drop_index('idx_asignaciones_asesor', table_name='asignaciones')
    op.drop_index('idx_clientes_empresa', table_name='clientes')
    op.drop_index('idx_leads_estado', table_name='leads')
    op.drop_index('idx_leads_punto_venta', table_name='leads')
    op.drop_index('idx_leads_empresa', table_name='leads')
    op.drop_table('lead_score')
    op.drop_table('lead_enriquecimiento')
    op.drop_table('asignaciones')
    op.drop_table('motos_disponibilidad')
    op.drop_table('leads')
    op.drop_table('asesores')
    op.drop_table('puntos_venta')
    op.drop_table('clientes')
    op.drop_table('motos_catalogo')
    op.drop_table('historico_cierres')
    op.drop_table('empresas')
    # ### end Alembic commands ###
